name: 'sphinx generate pdf'
description: 'sphinx generate pdf'
branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  commands:
    description: 'execute comannds'
    required: false

runs:
  using: 'docker'
  image: ''
  args:
    - ${{ inputs.doc-dirs }}
    - ${{ inputs.hugo-arguments }}
    - ${{ inputs.rsync-arguments }}
